version = 3.11.5
runner.dialect = scala213
preset = default
maxColumn = 120
project.git = true
docstrings.style = SpaceAsterisk
align.preset = most
align.multiline = true
align.tokens."+" = [
  {code = "=>", owner = "Case"}
]
newlines.alwaysBeforeMultilineDef = false
newlines.penalizeSingleSelectMultiArgList = false
lineEndings = preserve
trailingCommas = preserve
binPack.parentConstructors = Oneline
includeCurlyBraceInSelectChains = false
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}
fileOverride {
  "glob:**/*.sbt" { runner.dialect = scala3 }
  "glob:**/scala-3/**" {
    runner.dialect = scala3
    maxColumn = 100
    align.multiline = false
    align.allowOverflow = false
    indent.main = 2
    indent.callSite = 2
    indent.defnSite = 2
    danglingParentheses.preset = true
    rewrite.trailingCommas.style = multiple
  }
}
project.excludePaths = [
  "glob:**/target/**",
  "glob:**/project/project/**",
  "glob:**/metals.sbt"
]
